services:
  - type: web
    name: interiority-website
    env: static
    buildCommand: npm run build
    publishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
